server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aiproject?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ENC(/aMnHCtZ+Y9lshZSskZc18CT5w50mdio78RWXdKROB6bVRK5OqZPhFvwQWXmT5mF)
    password: ENC(Vb6MhnX4Gu2UFqX4oaUr3fE85Rt2SWackSjyLLzAy+6Jck8hY7NOgbTgLKHfzUI7)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


